### ISSUE TITLE
Please provide a tool with which you can embed blocks as UDP segments in a TS file so that bitcoinsatellite accepts the blocks.

### ISSUE THREAD

**Issue by VDelport** [Blockstream/bitcoinsatellite#2]
I tried to embed blocks in TS packages with tsp and the mpeinject option so that bitcoinsatellite accepts the blocks. I used netcat for this. Unfortunately bitcoinsattellite does not accept these blocks. I then used Wireshark to analyze the TS file, which you kindly provided me, and saw that you packed the UDP segments into the TS packages very efficiently, so that the last fragment of a UDP segment and the first Fragment of the subsequent UDP segment are packed into one and the same TS packet (section packing).

I assume that you have developed your own tool for this? Is the tool open source and would you make it available on your git repository?

**Comment by blockstreamsatellite** [comment]
We are closing this issue now, as it relates to the solution discussed in https://github.com/Blockstream/satellite/issues/83 . 

Thanks again.
