### ISSUE TITLE
Attempt to compile bitcoinsatellite on Linux Mint 19 Cinnamon fails

### ISSUE THREAD

**Issue by VDelport** [Blockstream/bitcoinsatellite#3]
I'm trying to compile bitcoinsatellite on Linux Mint 19 Cinnamon with the following build or compiler options:

Build Options:
  with endomorphism   = no
  with ecmult precomp = yes
  with jni            = no
  with benchmarks     = no
  with coverage       = no
  module ecdh         = no
  module recovery     = yes

  asm                 = x86_64
  bignum              = no
  field               = 64bit
  scalar              = 64bit

  CC                  = gcc
  CFLAGS              = -g -O2 -W -std=c89 -pedantic -Wall -Wextra -Wcast-align -Wnested-externs -Wshadow -Wstrict-prototypes -Wno-unused-function -Wno-long-long -Wno-overlength-strings -fvisibility=hidden -O3
  CPPFLAGS            = 
  LDFLAGS             = 

Fixing libtool for -rpath problems.

Options used to compile and link:
  with wallet   = no
  with gui / qt = no
  with zmq      = no
  with test     = yes
    with prop   = no
    with fuzz   = no
  with bench    = yes
  with upnp     = no
  use asm       = yes
  sanitizers    = 
  debug enabled = no
  gprof enabled = no
  werror        = no

  target os     = linux
  build os      = 

  CC            = gcc
  CFLAGS        = -g -O2
  CPPFLAGS      =   -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2  -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS
  CXX           = g++ -std=c++11
  CXXFLAGS      =   -fstack-reuse=none -Wstack-protector -fstack-protector-all     -O2
  LDFLAGS       = -pthread  -Wl,-z,relro -Wl,-z,now -pie  
  ARFLAGS       = cr

I get the following error message:

In file included from wirehair/gf256.h:70:0,
                 from wirehair/gf256.cpp:30:
/usr/lib/gcc/x86_64-linux-gnu/7/include/tmmintrin.h: In function ‘void gf256_mul_mem(void*, const void*, uint8_t, int)’:
/usr/lib/gcc/x86_64-linux-gnu/7/include/tmmintrin.h:136:1: error: inlining failed in call to always_inline ‘__m128i _mm_shuffle_epi8(__m128i, __m128i)’: target specific option mismatch
 _mm_shuffle_epi8 (__m128i __X, __m128i __Y)
 ^~~~~~~~~~~~~~~~
wirehair/gf256.cpp:1244:16: note: called from here
             h0 = _mm_shuffle_epi8(table_hi_y, h0);
             ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from wirehair/gf256.h:70:0,
                 from wirehair/gf256.cpp:30:
/usr/lib/gcc/x86_64-linux-gnu/7/include/tmmintrin.h:136:1: error: inlining failed in call to always_inline ‘__m128i _mm_shuffle_epi8(__m128i, __m128i)’: target specific option mismatch
 _mm_shuffle_epi8 (__m128i __X, __m128i __Y)
 ^~~~~~~~~~~~~~~~
wirehair/gf256.cpp:1243:16: note: called from here
             l0 = _mm_shuffle_epi8(table_lo_y, l0);
             ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from wirehair/gf256.h:70:0,
                 from wirehair/gf256.cpp:30:
/usr/lib/gcc/x86_64-linux-gnu/7/include/tmmintrin.h:136:1: error: inlining failed in call to always_inline ‘__m128i _mm_shuffle_epi8(__m128i, __m128i)’: target specific option mismatch
 _mm_shuffle_epi8 (__m128i __X, __m128i __Y)
 ^~~~~~~~~~~~~~~~
wirehair/gf256.cpp:1244:16: note: called from here
             h0 = _mm_shuffle_epi8(table_hi_y, h0);
             ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from wirehair/gf256.h:70:0,
                 from wirehair/gf256.cpp:30:
/usr/lib/gcc/x86_64-linux-gnu/7/include/tmmintrin.h:136:1: error: inlining failed in call to always_inline ‘__m128i _mm_shuffle_epi8(__m128i, __m128i)’: target specific option mismatch
 _mm_shuffle_epi8 (__m128i __X, __m128i __Y)
 ^~~~~~~~~~~~~~~~
wirehair/gf256.cpp:1243:16: note: called from here
             l0 = _mm_shuffle_epi8(table_lo_y, l0);
             ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Makefile:8091: recipe for target 'wirehair/libbitcoin_server_a-gf256.o' failed
make[2]: *** [wirehair/libbitcoin_server_a-gf256.o] Error 1
make[2]: Verzeichnis „/home/blocksatdvbs2/install/bitcoinsatellite/bitcoinsatellite/src“ wird verlassen
Makefile:13462: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Verzeichnis „/home/blocksatdvbs2/install/bitcoinsatellite/bitcoinsatellite/src“ wird verlassen
Makefile:774: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by 3cl1ps** [comment]
hey, got the same issue with raspbian. You should use ubuntu and pull directly from ppa.

what arch are you using ? tmmintrin.h errors are because you're trying to compile with SSE3 instructions.

what i did to compile wirehair, try commenting lines 56 & 58 from https://github.com/Blockstream/bitcoinsatellite/blob/master/src/wirehair/gf256.h :
//#if defined(ANDROID) || defined(IOS) || defined(LINUX_ARM)
    #define GF256_TARGET_MOBILE
//#endif // ANDROID

**Comment by blockstreamsatellite** [comment]
Hi @VDelport ,

We are closing this old issue now. It is related to the problem discussed in #6 , which has a new solution now on the most recent release (version 0.2.3). More details about the solution are available on the [release notes](https://github.com/Blockstream/bitcoinsatellite/blob/master/doc/release-notes/satellite/release-notes-0.2.3.md#simd-compatibility).

Thanks
