### ISSUE TITLE
error compiling tbs drivers

### ISSUE THREAD

**Issue by 3cl1ps** [Blockstream/bitcoinsatellite#4]
hey i got this error after starting blocksat-cli deps install

hw : Raspberry Pi 4 Model B Rev 1.2
os : Ubuntu 20.04.1 LTS 64bits

ERROR: "__devm_regmap_init_sccb" [/home/ubuntu/.blocksat/src/tbsdriver/media_build/v4l/ov9650.ko] undefined!
make[3]: *** [scripts/Makefile.modpost:94: __modpost] Error 1
make[2]: *** [Makefile:1673: modules] Error 2
make[2]: Leaving directory '/usr/src/linux-headers-5.4.0-1022-raspi'
make[1]: *** [Makefile:53: default] Error 2
make[1]: Leaving directory '/home/ubuntu/.blocksat/src/tbsdriver/media_build/v4l'
make: *** [Makefile:26: all] Error 2
Traceback (most recent call last):
  File "/usr/local/bin/blocksat-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/blocksatcli/main.py", line 60, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/blocksatcli/dependencies.py", line 547, in drivers
    runner.run(["make", nproc_arg], cwd = media_build_dir)
  File "/usr/local/lib/python3.8/dist-packages/blocksatcli/util.py", line 239, in run
    res.check_returncode()
  File "/usr/lib/python3.8/subprocess.py", line 444, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['make', '-j4']' returned non-zero exit status 2.

same errror on tbs forum : 
https://www.tbsdtv.com/forum/viewtopic.php?f=87&t=25419&start=10

**Comment by 3cl1ps** [comment]
kernel version : 
Linux ubuntu 5.4.0-1022-raspi aarch64 

found this in https://github.com/Blockstream/satellite/blob/master/blocksatcli/dependencies.py
    # FIXME: Temporary workaround for error "modpost: "__devm_regmap_init_sccb"
    # ov9650.ko undefined!": disable ov9650 from the build.
    if (distro.id() == "fedora"):

replacing fedora with ubuntu works

**Comment by blockstreamsatellite** [comment]
Hi @3cl1ps ,

We are closing some old inactive issues on github. It looks like this issue was related to your other in https://github.com/Blockstream/satellite/issues/85, right?

Thanks
